
name: real_money_game
description: A real money earning game.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.5.0

flutter:
  uses-material-design: true
